### ISSUE TITLE
[Feature+Bug] MFT support

### ISSUE THREAD

**Issue by Monniasza** [Kerbas-ad-astra/SMURFF#10]
It is both a feature request and a bug report because MFT tanks keep their original mass ratio, not a realistic one. Changes included in connected pull request: https://github.com/Kerbas-ad-astra/SMURFF/pull/11

Example:
Install SMURFF, MFT, and fuel tank with MFT compatibility (referred to as X)

Add X
The X stays at the unmodified ratio of ~88%

Example with FL-T800
The indicated mass in part chooser is 4119kg
The actual mass is 4500kg after placement

**Comment by Monniasza** [comment]
@Kerbas-ad-astra, please prepare changes in a new pull request.

**Comment by Kerbas-ad-astra** [comment]
I don't use MFT, so it's not a priority for me to spend time developing MFT compatibility.  If you provide a PR that meets my requirements (i.e. multiplies the tank mass by a factor raised to the power of tanklever -- see e.g. the few lines starting at https://github.com/Kerbas-ad-astra/SMURFF/blob/master/GameData/SMURFF/SMURFF.cfg#L35 for an example of how to do this with Module Manager), I will test it and consider accepting it.

**Comment by Monniasza** [comment]
Created pull request.

**Comment by Monniasza** [comment]
@Kerbas-ad-astra Do you plan to post this update? Please announce it on the forum.
